# Generated by Django 5.1.1 on 2024-10-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credit',
            field=models.IntegerField(default=10),
        ),
    ]
