# Generated by Django 5.0.7 on 2024-07-21 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(max_length=255)),
                ('video_id', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_name', models.CharField(max_length=255)),
                ('original_language', models.CharField(max_length=50, null=True)),
                ('duration', models.CharField(max_length=8, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='contents.video')),
            ],
        ),
    ]
