# Generated by Django 5.0.7 on 2024-07-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.JSONField(null=True, blank=True),
        ),
    ]
