# Generated by Django 5.0.7 on 2024-08-01 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_transcript_transcript_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_id',
            new_name='youtube_video_id',
        ),
    ]
