# Generated by Django 5.0.7 on 2024-08-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_rename_video_id_video_youtube_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
