# Generated by Django 5.0.7 on 2024-07-29 04:02

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations, models


def set_default_user(apps, schema_editor):
    Comment = apps.get_model('interactions', 'Comment')
    Vote = apps.get_model('interactions', 'Vote')
    
    # Assuming you have a user with ID=1 that you want to set as the default
    default_user = User.objects.get(id=1)
    
    Comment.objects.filter(user__isnull=True).update(user=default_user)
    Vote.objects.filter(user__isnull=True).update(user=default_user)

class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_vote_user_alter_vote_unique_together_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_default_user),
    ]
