# Generated by Django 5.0.7 on 2024-08-23 05:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_alter_comment_note_alter_vote_note'),
        ('notes', '0008_note_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('owner', 'note')},
        ),
    ]
