# Generated by Django 5.0.7 on 2024-07-27 04:23

from django.db import migrations, models

def create_default_list(apps, schema_editor):
    # create an agent role first as it is required to create a list.
    AgentRole = apps.get_model('ai_agent', 'AgentRole')
    default_agent_role = AgentRole.objects.create(description="Sumarize this content")
    List = apps.get_model('lists', 'List')
    default_list = List.objects.create(name='Default List', description='This is the default list')
    Note = apps.get_model('notes', 'Note')
    for note in Note.objects.all():
        note.note_list = default_list
        note.save()



class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('lists', '0001_initial'),
        ('ai_agent', '0001_initial'),  # Added this line to fix migration
    ]

    operations = [
        migrations.RunPython(create_default_list),
    ]
