# Generated by Django 5.0.7 on 2024-07-27 04:23

from django.db import migrations, models

def create_default_list(apps, schema_editor):
    List = apps.get_model('lists', 'List')
    default_list = List.objects.create(name='Default List', description='This is the default list')
    Note = apps.get_model('notes', 'Note')
    for note in Note.objects.all():
        note.note_list = default_list
        note.save()



class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_list),
    ]
