# Generated by Django 5.0.7 on 2024-07-27 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_remove_list_notes_alter_list_agent_role_and_more'),
        ('notes', '0002_auto_20240727_0423'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_list',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='lists.list'),
        ),
        migrations.AddField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
