# Generated by Django 5.0.7 on 2024-07-29 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_remove_list_notes_alter_list_agent_role_and_more'),
        ('notes', '0003_note_note_list_note_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AlterField(
            model_name='note',
            name='note_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.list'),
        ),
        migrations.AlterField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
