# Generated by Django 5.0.7 on 2024-07-30 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0012_alter_agentresponse_agent_role'),
        ('notes', '0006_note_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='response',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='ai_agent.agentresponse'),
            preserve_default=False,
        ),
    ]
