# Generated by Django 5.0.7 on 2024-07-27 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0003_agentrole_name'),
        ('lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='notes',
        ),
        migrations.AlterField(
            model_name='list',
            name='agent_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ai_agent.agentrole'),
        ),
        migrations.AlterField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
