# Generated by Django 5.0.7 on 2024-07-30 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0011_alter_agentresponse_agent_role'),
        ('lists', '0003_alter_list_options_alter_list_agent_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='agent_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_agent.agentrole'),
        ),
    ]
