# Generated by Django 5.0.7 on 2024-08-05 00:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_alter_list_agent_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
