# Generated by Django 5.1.1 on 2024-09-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_list_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='meta_description',
            field=models.SlugField(blank=True, max_length=150), # also added the meta_description field
        ),
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.SlugField(blank=True, max_length=60), # also added the meta_description field
        ),
    ]
