# Generated by Django 5.1.1 on 2024-09-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_list_meta_description_list_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
