# Generated by Django 5.0.7 on 2024-07-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0002_agentrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrole',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
