# Generated by Django 5.0.7 on 2024-07-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0004_alter_agentrole_options_alter_response_options'),
        ('contents', '0003_alter_transcript_transcript_text'),
        ('notes', '0004_alter_note_options_remove_note_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='AgentResponse',
        ),
        migrations.AlterModelOptions(
            name='agentresponse',
            options={'ordering': ['-created_at'], 'verbose_name': 'AgentResponse', 'verbose_name_plural': 'AgentResponses'},
        ),
    ]
