# Generated by Django 5.0.7 on 2024-07-29 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0005_rename_response_agentresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentresponse',
            name='agent_role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ai_agent.agentrole'),
            preserve_default=False,
        ),
    ]
