# Generated by Django 5.0.7 on 2024-07-30 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0009_alter_agentresponse_agent_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentresponse',
            name='agent_role',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='agent_responses', to='ai_agent.agentrole'),
        ),
    ]
