# Generated by Django 5.0.7 on 2024-07-31 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0012_alter_agentresponse_agent_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
